[package]
name = "say-my-name"
version = "0.1.0"
authors = ["James Rogers <j.rogers10@uni.brighton.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
